stages:
  prepare_dataset:
    cmd: python src/stages/prepare_dataset.py
    deps:
    - src/stages/prepare_dataset.py
    - src/config.yaml
    - ./data/Housing.csv
    outs:
    - ./data/final.csv
  data_split:
    cmd: python src/stages/data_splite.py
    deps:
    - src/stages/data_splite.py
    - src/config.yaml
    - ./data/final.csv
    outs:
    - ./data/test_housing.csv
    - ./data/train_housing.csv
  train:
    cmd: python src/stages/train.py
    deps:
    - src/config.yaml
    - src/stages/train.py
    - ./data/test_housing.csv
    - ./data/train_housing.csv
    outs:
    - ./models/model.joblib
    - ./models/power.joblib
  test_model:
    cmd: python src/stages/test_model.py
    deps:
    - src/config.yaml
    - src/stages/test_model.py
    - ./models/model.joblib
    - ./models/power.joblib
    - ./data/test_housing.csv
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
